
export const REQUEST_COUNTRY_DATA = 'REQUEST_COUNTRY_DATA';

export const RESPONSE_COUNTRY_DATA = 'RESPONSE_COUNTRY_DATA';

export const COUNTRY_DATA_ERROR = 'COUNTRY_DATA_ERROR';

export const ADD_SEARCH_COUNTRY_DATA = 'ADD_SEARCH_COUNTRY_DATA';

export const REQUEST_COUNTRY_DATA_NAME = 'REQUEST_COUNTRY_DATA_NAME';

export const RESPONSE_COUNTRY_DATA_NAME = 'RESPONSE_COUNTRY_DATA_NAME';

export const COUNTRY_DATA_NAME_ERROR = 'COUNTRY_DATA_NAME_ERROR';

export const RESET_SEARCH_COUNTRY_DATA = 'RESET_SEARCH_COUNTRY_DATA';

export const ADD_SEARCH_COUNTRY_ITEM = 'ADD_SEARCH_COUNTRY_ITEM';

export const REMOVE_SEARCH_COUNTRY_ITEM = 'REMOVE_SEARCH_COUNTRY_ITEM';


