
export const REQUEST_COUNTRY_DATA = 'REQUEST_COUNTRY_DATA';

export const RESPONSE_COUNTRY_DATA = 'RESPONSE_COUNTRY_DATA';

export const COUNTRY_DATA_ERROR = 'COUNTRY_DATA_ERROR';

export const ADD_SEARCH_COUNTRY_DATA = 'ADD_SEARCH_COUNTRY_DATA';

